pipeline {
  agent any
  environment {
    AWS_ACCESS_KEY_ID = credentials('aws-access-key')
    AWS_SECRET_ACCESS_KEY = credentials('aws-secret-key')
  }
  stages {
    stage('Checkout') {
      steps { checkout scm }
    }
    stage('Terraform') {
      steps {
        sh 'cd terraform && terraform init && terraform apply -auto-approve'
        sh 'cd .. && terraform output -json > terraform_outputs.json'
      }
    }
    stage('Generate Inventory') {
      steps {
        sh 'python3 ansible/generate_inventory.py'
        sh 'cat ansible/inventory.ini'
      }
    }
    stage('Ansible Setup') {
      steps {
        sh 'ansible-playbook -i ansible/inventory.ini ansible/playbook_setup.yml -v'
        sh 'ansible-playbook -i ansible/inventory.ini ansible/playbook_swarm.yml -v'
        sh 'ansible-playbook -i ansible/inventory.ini ansible/playbook_deploy.yml -v'
      }
    }
  }
}
